import data from "../data/employee.json"
import styles from '../styles/About.module.css'
import { useState } from "react"
import EmployeeCard from "../components/EmployeeCard"
import Link from "next/link"
import Head from "next/head"
import Header from '../components/Header'
import SectionHeader from '../components/SectionHeader'
import sectionData from '../data/sections.json'


export default function About() {
    const [employee, setEmployee] = useState([...data])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet" />

            </Head>
            <main>
                <Header />
                {
                    sectionData && sectionData.map((info, index) => {
                        if (info.id == 1) {
                            return (
                                <SectionHeader key={index} content={info.section} />
                            )
                        }
                    })
                }
                <div className={styles.employeeCard__container}>
                    {
                        employee && employee.map((info, index) => {
                            return <EmployeeCard key={index} name={info.name} role={info.role} bio={info.bio} />
                        })
                    }
                </div>
            </main>
        </>
    )
}