import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Header from '../components/Header'
const inter = Inter({ subsets: ['latin'] })
import SectionHeader from '../components/SectionHeader'
import sectionData from '../data/sections.json'

export default function Home() {
  console.log(data)
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Candy Land College</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet" />
      </Head>
      <header>
        <Header />
      </header>
      <main className={styles.main}>
        {
          sectionData && sectionData.map((info, index) => {
            if (info.id == 0) {
              return (
                <SectionHeader key={index} content={info.section} />
              )
            }
          })
        }
        <div className={`${styles.programs__container}`}>
          {
            information && information.map((info, index) => {
              if (info.department.toLowerCase() === 'business') {
                return (
                  <Card key={index} department={info.department} degree={info.degree} font="30px" />
                )
              }
              if (info.department.toLowerCase() === 'computing') {
                return (
                  <Card key={index} department={info.department} degree={info.degree} font="30px" />
                )
              }
            })
          }
        </div>
      </main>
    </>
  )
}
